name: dependency-updates
on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  certbot-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: update certbot version
        id: update
        run: |
          CB_VERSION="$(
          git ls-remote --tags https://github.com/certbot/certbot \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed "s|\^{}||g" \
              | sed "s|v||g"
          )"
          CBDM_VERSION="$(
          git ls-remote --tags https://github.com/alexzorin/certbot-dns-multi \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1
          )"
          sed -i "s|certbot==.*|certbot==$CB_VERSION|" Dockerfile
          sed -i "s|certbot-dns-cloudflare==.*|certbot-dns-cloudflare==$CB_VERSION|" Dockerfile
          sed -i "s|certbot-dns-multi==.*|certbot-dns-multi==$CBDM_VERSION|" Dockerfile
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          signoff: true
          delete-branch: true
          commit-message: update certbot version
          branch: update-certbot-version
          title: update certbot version
          body: update certbot version
